import { montserrat } from "./ui/font";
import "./ui/global.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Header from "@/app/ui/pagelayout/header";
import Footer from "@/app/ui/pagelayout/footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} bg-black`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
