import { montserrat } from './ui/font';
import './ui/global.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${montserrat.className}`} >{children}</body>
    </html>
  )
}
